# Generated by Django 3.2.9 on 2022-06-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientId', models.AutoField(primary_key=True, serialize=False)),
                ('ClientUsername', models.CharField(max_length=50)),
                ('ClientName', models.CharField(max_length=50)),
                ('ClientAge', models.IntegerField()),
                ('ClientWeight', models.FloatField()),
                ('ClientHeight', models.FloatField()),
                ('ClientGender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('ExcerciseId', models.AutoField(primary_key=True, serialize=False)),
                ('ExcerciseName', models.CharField(max_length=50)),
                ('ExcercisePhoto', models.ImageField(upload_to='')),
                ('ExcerciseDescription', models.TextField()),
                ('ExcerciseMuscle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('RoutineId', models.AutoField(primary_key=True, serialize=False)),
                ('RoutineName', models.CharField(max_length=50)),
                ('RoutineExcercises', models.ManyToManyField(to='gimnasioaApp.Excercise')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HistoryWeight', models.FloatField()),
                ('HistoryDate', models.DateField()),
                ('HistoryClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasioaApp.client')),
                ('HistoryRoutineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasioaApp.routine')),
            ],
        ),
    ]
